### ISSUE TITLE
Support Chart.js v4

### ISSUE THREAD

**Issue by ximex** [xr0master/chartjs-react#19]
Please update to support Chart.js v4

https://github.com/chartjs/Chart.js/releases/tag/v4.0.0-release
https://github.com/chartjs/Chart.js/releases/tag/v4.0.1
https://www.chartjs.org/docs/latest/migration/v4-migration.html

**Comment by xr0master** [comment]
@ximex Hi, thanks for letting me know version 4 has been released. Definitely I will update the library soon.

**Comment by xr0master** [comment]
@ximex the current version (3.8) fully supports version 4 and does not require urgent changes.

After some time, I will release a new version with minor changes in the documentation. The code does not require changes.

**Comment by xr0master** [comment]
new version published
