### ISSUE TITLE
Problem installing chartjs-react.

### ISSUE THREAD

**Issue by jch02140** [xr0master/chartjs-react#5]
I am using npm 7.3.0 and when I try to install the module it gives the following errors.

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: currency-app@0.1.0
> npm ERR! Found: chart.js@2.9.4
> npm ERR! node_modules/chart.js
> npm ERR!   chart.js@"^2.9.4" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer chart.js@">=3.0.0-beta.7" from chartjs-react@3.1.5
> npm ERR! node_modules/chartjs-react
> npm ERR!   chartjs-react@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-01-03T19_04_16_708Z-debug.log

I have to use --force option to install it. Hope this will be fixed...

**Comment by xr0master** [comment]
Hey. Thank you.
Unfortunately this looks like an issue with npm v7, it can't install peer dependencies with beta.
Please run
```sh
npm i chart.js@3.0.0-beta.7 chartjs-react --save
```
